services:
  control-panel-backend:
    image: ghcr.io/siryus-org/control-panel-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"

  control-panel-frontend:
    image: ghcr.io/siryus-org/control-panel-frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - control-panel-backend
